name: Build_APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip openjdk-17-jdk unzip wget
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      - name: Install Android SDK and Build-Tools
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          cd $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          
          # قبول تمام License ها
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
          
          # نصب Build-Tools و Platform
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platforms;android-33" "build-tools;36.1.0"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyRubBot
          path: bin/*.apk
